sudo: false
language: ruby
script:
  - g++ -v
  - bundle install
  - bundle exec rubocop --version
  - bundle exec rubocop -D .
  - bundle exec rspec --backtrace
  - cd Relay
  - bundle install
  - bundle exec arduino_ci_remote.rb
